import Head from "next/head";
import React from "react";
import Link from "next/link";
import { env } from "@/env.mjs";
import axios from "axios";

export default function Home() {
  const [companies, setCompanies] = React.useState<[]>([]);

  React.useEffect(() => {
    axios
      .get(env.NEXT_PUBLIC_BACKEND_BASE_URL + "/dashboard/companies")
      .then((res) => {
        setCompanies(res.data.data); // Assuming the response data is an array of companies
      })
      .catch((err) => {
        console.log(err);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Carta Online</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav>
          <h1>
            <Link href="/">Carta Online</Link>
          </h1>
          <Link href="/register">Registrar un local</Link>
        </nav>
        <p className="mt-6 leading-7"></p>
        <div>
          {companies.map((company) => (
            <div key={company.name}>
              <p>{company.name}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
