import Head from "next/head";
import React from "react";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Carta Online</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav>
          <h1>
            <Link href="/">Carta Online</Link>
          </h1>
          <Link href="/register">Registrar un local</Link>
        </nav>
        <p className="leading-7 [&:not(:first-child)]:mt-6"></p>
        <div>
          <h2>Locales</h2>

          <ul></ul>
        </div>
      </main>
    </>
  );
}
