import Head from "next/head";
import { env } from "@/env.mjs";
import React from "react";
import axios from "axios";
import { type Company } from "./register";
import Link from "next/link";
import { AuthContext } from "@/components/global/AuthProvider";

export default function Home() {
  const [companies, setCompanies] = React.useState<Company[]>([]);
  const { user } = React.useContext(AuthContext);

  React.useEffect(() => {
    axios
      .get<Company[]>(
        env.NEXT_PUBLIC_BACKEND_BASE_URL + "/api/dashboard/companies"
      )
      .then((res) => {
        setCompanies(res.data);
      })
      .catch((err) => {
        console.log(err);
      });
  }, []);
  return (
    <>
      <Head>
        <title>Carta Online</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav>
          <h1>
            <Link href="/">Carta Online</Link>
          </h1>
          <Link href="/register">Registrar un local</Link>
        </nav>
        <p className="leading-7 [&:not(:first-child)]:mt-6"></p>
        <div>
          <h2>Locales</h2>
          <h3>{user}</h3>
          <ul></ul>
        </div>
      </main>
    </>
  );
}
